server:
  ip: localhost
  port: 9000
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:jdbc:h2: file:D:/H2/bin/test
#    url:jdbc:h2: mem:test
    username: sa
    password: 123
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
#    initialization-mode: always
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #注意加上
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  servlet:
     multipart:
        max-file-size: 100MB
        max-request-size: 100MB
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/毕设/files/
